// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCylKoCwtiCN2gTYn8fq3BHFN39H1IwBn4',
    appId: '1:15215110783:web:d06ab731b9eba27690ad4a',
    messagingSenderId: '15215110783',
    projectId: 'tp3flutter-480c6',
    authDomain: 'tp3flutter-480c6.firebaseapp.com',
    storageBucket: 'tp3flutter-480c6.appspot.com',
    measurementId: 'G-4TT144BXR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDts6zS5gwtFq0jF0AazXRdG3cP3hjx2cI',
    appId: '1:15215110783:android:4c2a9119a9c97daf90ad4a',
    messagingSenderId: '15215110783',
    projectId: 'tp3flutter-480c6',
    storageBucket: 'tp3flutter-480c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq8Qg4gpePCfeMxTfb1Tdt_6bR-tUto_4',
    appId: '1:15215110783:ios:f6775e5216de5ac090ad4a',
    messagingSenderId: '15215110783',
    projectId: 'tp3flutter-480c6',
    storageBucket: 'tp3flutter-480c6.appspot.com',
    iosClientId: '15215110783-jems9cptufrjd1sdqm1ft9ffdjlohu94.apps.googleusercontent.com',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq8Qg4gpePCfeMxTfb1Tdt_6bR-tUto_4',
    appId: '1:15215110783:ios:f6775e5216de5ac090ad4a',
    messagingSenderId: '15215110783',
    projectId: 'tp3flutter-480c6',
    storageBucket: 'tp3flutter-480c6.appspot.com',
    iosClientId: '15215110783-jems9cptufrjd1sdqm1ft9ffdjlohu94.apps.googleusercontent.com',
    iosBundleId: 'com.example.tp2',
  );
}
